name: my_flutter_app
description: A new Flutter project with Firebase integration.

publish_to: "none"  # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1 
  # Firebase core
  firebase_core: ^4.1.0               # Latest stable Firebase Core :contentReference[oaicite:0]{index=0}

  # Firebase Authentication
  firebase_auth: ^6.0.2               # Latest stable Firebase Auth :contentReference[oaicite:1]{index=1}

  # Cloud Firestore
  cloud_firestore: ^6.0.1             # Latest stable Cloud Firestore :contentReference[oaicite:2]{index=2}

  # Helpful icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.0.5
  
  fl_chart: ^0.67.0            # For doughnut charts
  syncfusion_flutter_gauges: ^25.2.3 # For budget gauges
  intl: ^0.19.0                # For date and number formatting
  font_awesome_flutter: ^10.7.0  # For FontAwesome icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add your assets or fonts here if needed
  # assets:
  #   - assets/images/

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
